### ISSUE TITLE
Missing xcolor package load

### ISSUE THREAD

**Issue by Ri0016** [Rmano/circledsteps#10]
It is written in the documentation that the package will load xcolor package, but it is not found in the .sty file. So some color setting does not work well if only circledsteps is loaded.

**Comment by Rmano** [comment]
You're right --- I switched from requiring `tikz` to just `pgfkeys` and forgot to add `xcolor`. 

Note to self: never rely on a package loading another one... 
Thanks,

**Comment by Rmano** [comment]
Will leave open --- I will wait a bit and then make a bugfix release on CTAN. Thanks!

**Comment by Rmano** [comment]
Reopening, I forgot this and didn't update the package...

**Comment by Rmano** [comment]
Released now, closing
