### ISSUE TITLE
Error on the "Support" link in the CTAN package page

### ISSUE THREAD

**Issue by quark67** [Rmano/circledsteps#3]
On https://www.ctan.org/pkg/circledsteps we read:
Support https://github.com/circuitikz/circuitikz/issues

It should be:
Support https://github.com/Rmano/circledsteps/issues

**Comment by Rmano** [comment]
I have sent a correction request to CTAN. Thanks!

**Comment by Rmano** [comment]
It has been fixed right now. Thanks for spotting it!
