### ISSUE TITLE
Add optional argument to Circled

### ISSUE THREAD

**Issue by Rmano** [Rmano/circledsteps#4]
A suggestion from @marmot https://chat.stackoverflow.com/transcript/message/48219666#48219666

> @Rmano I have a feature request. Is it possible to redefine `\Circled` to become something like
```
\newcommand{\CCircled}[2][]{\begingroup
\pgfkeys{/csteps/.cd,inner color=.,#1}%
\ifmmode
\Circled{$#2$}%
\else
\Circled{#2}%
\fi
\endgroup}
```
> and similarly for the other commands? That is, add an optional argument that allows one to set the pgf keys? Also, maybe say in the manual that one can use `\pgfkeys` instead of `\tikzset` since the latter is not always loaded. And perhaps mention that the user needs to load `xcolor` to make use of the colors.
>   

> @Rmano tikzmark has means of detecting pretty much everything about the ambient settings, i.e. it goes far beyond what I did here with \ifmmode. That is, if you are wondering how to carry the outside settings into the circle, this has already been done in the tikzmark library.

**Comment by ghost** [comment]
Next time I know what the proper way to bring this up is. ;-)

**Comment by Rmano** [comment]
@tallmarmot  Hi, I'm back --- from vacation off-line (what a nice thing). 
I like the proposal --- do you want to propose a PR or are you ok if I code and merge it? If you give me an email (even a fake one you like, as for example tallmarmot@github.com) I can co-attribute the code, as I did for example in several commits on circuitikz.

**Comment by ghost** [comment]
I would like to suggest to make \Circled also figure out if we are in a subscript, say. This can be done by slightly enhancing the definition of `\CircledParamOpts` to become (this is shamelessly adapted from the tikzmark library and I am not sure I am doing it right but in simple tests it seems to work)

```
\newcommand{\CircledParamOpts}[3]{%
    \begingroup
        \pgfkeys{/csteps/.cd, #1}%
        \ifmmode
		\mathchoice{%
        \csteps@CircledParam{#2}{$\displaystyle #3$}%
		}{%
        \csteps@CircledParam{#2}{$\textstyle #3$}%
		}{%
        \csteps@CircledParam{#2}{$\scriptstyle#3$}%
		}{%
        \csteps@CircledParam{#2}{$\scriptscriptstyle#3$}%
		}%
        \else
        \csteps@CircledParam{#2}{#3}%
        \fi
    \endgroup
}
```

Then one could have for instance

```
\documentclass{article}
\usepackage{xcolor}
\usepackage{circledsteps}

\begin{document}
\[\Circled[outer color=red]{x}\]
\[\int\limits_{-1}^1\!\mathrm{d}x\,f_{\ell_1}(x)\]
\[\Circled[outer color=blue]{\int\limits_{-1}^1}\!
\Circled[outer color=orange]{\mathrm{d}x}
f_{\Circled[outer color=red]{\ell}_{\Circled[outer color=cyan]{1}}}(x)\]
\end{document}
```

<img width="293" alt="Screen Shot 2020-01-08 at 8 04 30 AM" src="https://user-images.githubusercontent.com/35985244/71994401-836a1880-31ed-11ea-991d-280cdd0eff3c.png">
