### ISSUE TITLE
Circles with black background

### ISSUE THREAD

**Issue by 0xYuval** [Rmano/circledsteps#5]
Hi! Is it possible to create a circle with a black background color and a white text color with the current version of the package? Thanks for help!

**Comment by Rmano** [comment]
As it is now, no --- I'll see if I can add the option.

**Comment by Rmano** [comment]
@0xYuval The main problem is that while there is a filled circle in `pict2e`, there is no filled oval... so it's not so simple to implement this.

**Comment by Rmano** [comment]
Do you like this?
![image](https://user-images.githubusercontent.com/6414907/72009499-56058500-3256-11ea-9ae5-0eede360cf89.png)

**Comment by 0xYuval** [comment]
> Do you like this?
> ![image](https://user-images.githubusercontent.com/6414907/72009499-56058500-3256-11ea-9ae5-0eede360cf89.png)

Yes, it looks great! Thanks!
