### ISSUE TITLE
Typo and missing word in manual

### ISSUE THREAD

**Issue by quark67** [Rmano/circledsteps#8]
On line 157 of https://github.com/Rmano/circledsteps/blob/master/circledsteps-manual.tex, we read:
```tex
\footnote{Notice that in the example the numbers in the references one the right are blue to to \texttt{hyperref} configuration!}
```

Isn't "on" better than "one", as the following?

```tex
\footnote{Notice that in the example the numbers in the references on the right are blue to to \texttt{hyperref} configuration!}
```

And isn't a missing word between "to" and "to" (`are blue to to`)?

Perhaps the word "correspond", but I'm not sure.

**Comment by Rmano** [comment]
Well spotted, will fix!
